const mongoose = require('mongoose');

// Ad Schema
const adSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },  // Reference to User
  content: { type: String, required: true },    // The ad text generated by GPT
  interactions: { type: Array, default: [] },   // Track user interactions
}, { timestamps: true });

module.exports = mongoose.model('Ad', adSchema);
